# Generated by Django 2.2 on 2019-10-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.IntegerField(choices=[(0, 's1'), (1, 's2'), (2, 's3'), (3, 's4'), (4, 's5')], default=0),
        ),
    ]
