# Generated by Django 2.2 on 2019-10-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
