# Generated by Django 2.2 on 2019-10-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='section',
            field=models.IntegerField(choices=[(0, 'CSE-IS'), (1, 'CSE-NS'), (2, 'CSE-CORE'), (3, 'IT')], default=3),
        ),
        migrations.AlterField(
            model_name='staff',
            name='year',
            field=models.IntegerField(choices=[(0, 'First Year'), (1, 'Second Year'), (2, 'Third Year'), (3, 'Fourth Year')], default=3),
        ),
    ]
