# Generated by Django 2.2 on 2019-10-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
