# Generated by Django 2.2 on 2019-10-27 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20191027_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='section',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='year',
        ),
    ]
