# Generated by Django 2.2 on 2019-10-30 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='student_id',
        ),
        migrations.AddField(
            model_name='marks',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marks',
            name='student',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='mark_profile', to='student.Student'),
            preserve_default=False,
        ),
    ]
