# Generated by Django 2.2 on 2019-10-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20191031_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='s1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marks',
            name='s2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marks',
            name='s3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marks',
            name='s4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marks',
            name='s5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='staff',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
